name: Deploy para EC2 Debian 13

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Testar conexão SSH
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no jocerlan@${{ secrets.EC2_HOST }} "echo ✅ Conexão OK!"

      - name: Deploy no servidor Debian 13
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes jocerlan@${{ secrets.EC2_HOST }} "
            set -e
            cd /home/jocerlan || exit

            if [ ! -d portifolio ]; then
              echo '📥 Clonando projeto pela primeira vez...'
              git clone https://github.com/jocerlan/portifolio.git portifolio
            else
              if [ ! -d portifolio/.git ]; then
                echo '⚠️ Pasta existe mas não é repositório Git, removendo...'
                rm -rf portifolio
                git clone https://github.com/jocerlan/portifolio.git portifolio
              else
                echo '🔄 Atualizando repositório existente...'
                cd portifolio
                git fetch origin main
                git reset --hard origin/main
                cd ..
              fi
            fi

            cd portifolio

            echo '🐳 Recriando container Docker...'
            sudo docker stop site-estatico || true
            sudo docker rm site-estatico || true
            sudo docker build -t site-estatico .
            sudo docker run -d --restart always -p 80:80 --name site-estatico site-estatico
            
            echo '✅ Deploy concluído com sucesso!'
          "
